publishing

diff --git a/orb/src/commands/changesets.yml b/orb/src/commands/changesets.yml
--- a/orb/src/commands/changesets.yml
+++ b/orb/src/commands/changesets.yml
@@ -26,64 +26,65 @@ parameters:
     default: "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
     description: "Name of github repository to which the release branches will be pushed. In the form of username/reponame"
 steps:
-  - name: Run the release action
-    command: |
-      # First we make sure we have node installed
-      if ! [ -x "$(command -v node)" ]; then
-        echo 'Missing node binary' >&2
-        exit 1
-      fi
-
-      # Now we check that we have a github token
-      export GITHUB_TOKEN="${<< parameters.githubTokenName >>}"
-      if [ -z "$GITHUB_TOKEN" ]; then
-          echo "Missing github token. Please make sure to authenticate to github before running the release command" >&2
+  - run:
+      name: Run the release action
+      command: |
+        # First we make sure we have node installed
+        if ! [ -x "$(command -v node)" ]; then
+          echo 'Missing node binary' >&2
           exit 1
-      fi
+        fi
 
-      # And we check that the script has been included
-      if [ -z "$CHANGESETS_ACTION_SCRIPT" ]; then
-          echo "Missing changesets action script. Please make sure to export it as CHANGESETS_ACTION_SCRIPT env variable" >&2
+        # Now we check that we have a github token
+        export GITHUB_TOKEN="${<< parameters.githubTokenName >>}"
+        if [ -z "$GITHUB_TOKEN" ]; then
+            echo "Missing github token. Please make sure to authenticate to github before running the release command" >&2
+            exit 1
+        fi
+
+        # And we check that the script has been included
+        if [ -z "$CHANGESETS_ACTION_SCRIPT" ]; then
+            echo "Missing changesets action script. Please make sure to export it as CHANGESETS_ACTION_SCRIPT env variable" >&2
+            exit 1
+        fi
+
+        # Some of the environment variables we need are not available as pipeline values
+
+        export GITHUB_REPOSITORY="<< parameters.githubReleaseRepository >>"
+        export GITHUB_SHA="${CIRCLE_SHA1}"
+
+
+        # And populate the ref short & long names
+        if [ -n "${CIRCLE_BRANCH}" ]; then
+          GITHUB_REF_NAME="${CIRCLE_BRANCH}"
+          GITHUB_REF="refs/heads/$GITHUB_REF_NAME"
+        elif [ -n "${CIRCLE_TAG}" ]; then
+          GITHUB_REF_NAME="${CIRCLE_TAG}"
+          GITHUB_REF="refs/tags/$GITHUB_REF_NAME"
+        else
+          echo "Pipeline is not running for a branch or a tag" >&2
           exit 1
-      fi
+        fi
 
-      # 
-      # Some of the environment variables we need are not available as pipeline values
-      # 
 
-      # We need to string manipulate the GITHUB_REPOSITORY into existence
-      export GITHUB_REPOSITORY="<< parameters.githubReleaseRepository >>"
+        # Setup an authenticated remote
+        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
 
-      # And populate the ref short & long names
-      if [ -n "$<< pipeline.git.branch >>" ]; then
-        GITHUB_REF_NAME="<< pipeline.git.branch >>"
-        GITHUB_REF="refs/heads/$GITHUB_REF_NAME"
-      elif [ -n "$<< pipeline.git.tag >>" ]; then
-        GITHUB_REF_NAME="<< pipeline.git.tag >>"
-        GITHUB_REF="refs/tags/$GITHUB_REF_NAME"
-      else
-        echo "Pipeline is not running for a branch or a tag" >&2
-        exit 1
-      fi
+        # Run the changesets action by piping the script to node
+        echo $CHANGESETS_ACTION_SCRIPT | node 
 
-      # Setup an authenticated remote
-      git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
+      environment:
+        # This will take the whole changesets script and place its contents into the CHANGESETS_ACTION_SCRIPT env variable
+        
+        # The github action script expects these as its inputs
+        INPUT_SETUPGITUSER: << parameters.setupGitUser >>
+        INPUT_CREATEGITHUBRELEASES: << parameters.createGithubReleases >>
+        INPUT_PUBLISH: << parameters.publish >>
+        INPUT_VERSION: << parameters.version >>
 
-      # Run the changesets action by piping the script to node
-      echo $CHANGESETS_ACTION_SCRIPT | node 
+        # These need to be setup for the action so the environment mimics the github workflow environment
+        GITHUB_SERVER_URL: https://github.com
+        GITHUB_API_URL: https://api.github.com
+        GITHUB_GRAPHQL_URL: https://api.github.com/graphql
 
-    environment:
-      # This will take the whole changesets script and place its contents into the CHANGESETS_ACTION_SCRIPT env variable
-      CHANGESETS_ACTION_SCRIPT: <<include(modules/changesets-action/dist/index.js)>>
-
-      # The github action script expects these as its inputs
-      INPUT_SETUPGITUSER: << parameters.setupGitUser >>
-      INPUT_CREATEGITHUBRELEASES: << parameters.createGithubReleases >>
-      INPUT_PUBLISH: << parameters.publish >>
-      INPUT_VERSION: << parameters.version >>
-
-      # These need to be setup for the action so the environment mimics the github workflow environment
-      GITHUB_SHA: << pipeline.git.revision >>
-      GITHUB_SERVER_URL: https://github.com
-      GITHUB_API_URL: https://api.github.com
-      GITHUB_GRAPHQL_URL: https://api.github.com/graphql
+        CHANGESETS_ACTION_SCRIPT: ""
